version: "3.8"

services:
    api:
        build: .
        ports:
            - "3000:3000"
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_NAME=petition_app
            - DATABASE_USER=root
            - DATABASE_PASS=root
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: petition_app
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
